### ISSUE TITLE
Showing unconfirmed transaction details

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/explorer#437] opened 2018-11-03 16:26 UTC
**Is your feature request related to a problem? Please describe.**
When dynamic fees kick in, some trx will take a lot more than 8 seconds to be forged/confirmed and currently you can't see any details about an unconfirmed trx in the explorer.

**Describe the solution you'd like**
How about to show the details of an unconfirmed transaction like Bitcoin and Ethereum explorers do. This way people will not load a 404 error page and wonder what is happening with their transaction.

<img width="1178" alt="screen shot 2018-11-03 at 18 17 24" src="https://user-images.githubusercontent.com/3462869/47954691-c26f5f00-df95-11e8-964b-f62133d9ca8d.png">
<img width="1157" alt="screen shot 2018-11-03 at 18 14 06" src="https://user-images.githubusercontent.com/3462869/47954694-c7341300-df95-11e8-957f-78f1b7533f21.png">

**Comment by zillionn** [comment] 2018-12-21 09:55
I can see transactions with `0 confirmations` now. Way to go!

**Comment by dated** [comment] 2018-12-21 09:58
Just to confirm, you can see the modified `404` page as pictured in #506?

**Comment by zillionn** [comment] 2018-12-21 10:07
But I don't see 404, I see `Confirmations: 0`!

**Comment by dated** [comment] 2018-12-21 10:14
This is most likely a bug, and probably fixed in the `core-2.0-explorer` branch.

**Comment by zillionn** [comment] 2018-12-21 10:49
Why bug, I like it!

**Comment by dated** [comment] 2018-12-21 10:55
I like it too but I'm working on a proper way to display unconfirmed transactions ;)

**Comment by doubled1c3** [comment] 2018-12-31 20:20
Cheers to @dated for working on a proper way to display unconfirmed transactions! Maybe even also have a main page for this in the menu item list?

**Comment by ItsANameToo** [comment] 2019-09-29 21:23
@dated did you do anything for this yet? 🤔

**Comment by dated** [comment] 2019-09-30 05:17
No, nothing has been done yet. In the worst case every node would need to be queried to get a proper overview of unconfirmed transactions.

**Comment by zillionn** [comment] 2019-09-30 06:26
Isn't it safe to pass the IP of the peer received the tx in the URL, so the explorer will query it?

**Comment by faustbrian** [comment] 2020-11-06 04:57
Closing this due to our new explorer being announced for release soon https://ark.io/blog/ark-explorer-40-first-look-block-explorer-reimagined.

**Closed by faustbrian** 2020-11-06 04:57 UTC
Labels: Type: Feature
